const DATABASE_NAME = '@gameplay';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_ANNOTATIONS = `${DATABASE_NAME}:annotations`;

export {
  COLLECTION_USERS,
  COLLECTION_ANNOTATIONS
}